apiVersion: v1
kind: Pod
metadata:
  name: portal-noticias
  labels:
    app: portal-noticias
spec:
  containers:
    - name: portal-noticias-container
      image: aluracursos/portal-noticias:1
      resources:
        limits:
          cpu: "0.3"
          memory: "512Mi"          
        requests:
          cpu: "0.3"
          memory: "512Mi"
      ports:
        - containerPort: 80
      envFrom:
        - configMapRef:
            name: portal-configmap
